//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cake.ReSharper.GlobalTools.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cake.ReSharper.GlobalTools.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Generated by JetBrains Inspect Code 2021.3.3 --&gt;&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;title&gt;Issues Report&lt;/title&gt;
        ///    &lt;style&gt;
        ///          dt { float: left; margin-right: 0.5em; }
        ///          dd { }
        ///        &lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;div&gt;
        ///      &lt;h1&gt;Solution ..\..\..\..\..\..\..\github\Cake.ReSharper.GlobalTools\Cake.ReSharper.GlobalTools.sln&lt;/h1&gt;
        ///    &lt;div&gt;
        ///        &lt;h2&gt;Project Cake.ReSharper.GlobalTools&lt;/h2&gt;
        ///        &lt;dl&gt;
        ///      &lt;dt&gt;src\C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReSharperInspectCodeHtmlReportWithViolations {
            get {
                return ResourceManager.GetString("ReSharperInspectCodeHtmlReportWithViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;problems&quot;: [
        ///    {
        ///      &quot;file&quot;: &quot;$PROJECT_DIR$\\src\\Cake.ReSharper.GlobalTools\\InspectCode\\ReSharperInspectCodeReportAnalyzerFactory.cs&quot;,
        ///      &quot;line&quot;: &quot;21&quot;,
        ///      &quot;offset&quot;: &quot;12&quot;,
        ///      &quot;length&quot;: 2,
        ///      &quot;module&quot;: &quot;Cake.ReSharper.GlobalTools..NETCoreApp,Version=v3.1&quot;,
        ///      &quot;package&quot;: &quot;&lt;default&gt;&quot;,
        ///      &quot;problem_class&quot;: {
        ///        &quot;name&quot;: null,
        ///        &quot;id&quot;: &quot;CSharpErrors&quot;,
        ///        &quot;severity&quot;: &quot;ERROR&quot;
        ///      },
        ///      &quot;highlighted_element&quot;: &quot;Re&quot;,
        ///      &quot;language&quot;: &quot;CSHARP&quot;,
        ///      &quot;des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReSharperInspectCodeJsonReport1WithViolations {
            get {
                return ResourceManager.GetString("ReSharperInspectCodeJsonReport1WithViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;problems&quot;: [
        ///    {
        ///      &quot;file&quot;: &quot;$PROJECT_DIR$\\src\\Cake.ReSharper.GlobalTools\\InspectCode\\ReSharperInspectCodeReportAnalyzerFactory.cs&quot;,
        ///      &quot;line&quot;: &quot;22&quot;,
        ///      &quot;offset&quot;: &quot;12&quot;,
        ///      &quot;length&quot;: 1,
        ///      &quot;module&quot;: &quot;Cake.ReSharper.GlobalTools..NETCoreApp,Version=v3.1&quot;,
        ///      &quot;package&quot;: &quot;&lt;default&gt;&quot;,
        ///      &quot;problem_class&quot;: {
        ///        &quot;name&quot;: &quot;Redundant discard designation&quot;,
        ///        &quot;id&quot;: &quot;RedundantDiscardDesignation&quot;,
        ///        &quot;severity&quot;: &quot;SUGGESTION&quot;
        ///      },
        ///      &quot;highlighted_element&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReSharperInspectCodeJsonReport2WithViolations {
            get {
                return ResourceManager.GetString("ReSharperInspectCodeJsonReport2WithViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;problems&quot;: [
        ///    {
        ///      &quot;file&quot;: &quot;$PROJECT_DIR$\\src\\Cake.ReSharper.GlobalTools\\CleanupCode\\ReSharperCleanupCodeAliases.cs&quot;,
        ///      &quot;line&quot;: &quot;90&quot;,
        ///      &quot;offset&quot;: &quot;23&quot;,
        ///      &quot;length&quot;: 30,
        ///      &quot;module&quot;: &quot;Cake.ReSharper.GlobalTools..NETCoreApp,Version=v3.1&quot;,
        ///      &quot;package&quot;: &quot;&lt;default&gt;&quot;,
        ///      &quot;problem_class&quot;: {
        ///        &quot;name&quot;: &quot;Type member is never used: Non-private accessibility&quot;,
        ///        &quot;id&quot;: &quot;UnusedMember.Global&quot;,
        ///        &quot;severity&quot;: &quot;SUGGESTION&quot;
        ///      },
        ///      &quot;highlighted_element [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReSharperInspectCodeJsonReport3WithViolations {
            get {
                return ResourceManager.GetString("ReSharperInspectCodeJsonReport3WithViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;problems&quot;: [
        ///    {
        ///      &quot;file&quot;: &quot;$PROJECT_DIR$\\src\\Cake.ReSharper.GlobalTools\\CleanupCode\\ReSharperCleanupCodeAliases.cs&quot;,
        ///      &quot;line&quot;: &quot;24&quot;,
        ///      &quot;offset&quot;: &quot;20&quot;,
        ///      &quot;length&quot;: 27,
        ///      &quot;module&quot;: &quot;Cake.ReSharper.GlobalTools..NETCoreApp,Version=v3.1&quot;,
        ///      &quot;package&quot;: &quot;&lt;default&gt;&quot;,
        ///      &quot;problem_class&quot;: {
        ///        &quot;name&quot;: &quot;Type is never used: Non-private accessibility&quot;,
        ///        &quot;id&quot;: &quot;UnusedType.Global&quot;,
        ///        &quot;severity&quot;: &quot;SUGGESTION&quot;
        ///      },
        ///      &quot;highlighted_element&quot;: &quot;ReSha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReSharperInspectCodeJsonReport4WithViolations {
            get {
                return ResourceManager.GetString("ReSharperInspectCodeJsonReport4WithViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution ..\..\..\..\..\..\..\github\Cake.ReSharper.GlobalTools\Cake.ReSharper.GlobalTools.sln
        ///    Project Cake.ReSharper.GlobalTools
        ///      src\Cake.ReSharper.GlobalTools\CleanupCode\ReSharperCleanupCodeAliases.cs:24 Class &apos;ReSharperCleanupCodeAliases&apos; is never used
        ///      src\Cake.ReSharper.GlobalTools\CleanupCode\ReSharperCleanupCodeAliases.cs:90 Method &apos;ReSharperCleanupCodeFromConfig&apos; is never used
        ///      src\Cake.ReSharper.GlobalTools\InspectCode\ReSharperInspectCodeAliases.cs:24 Class &apos;ReSharperInspe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReSharperInspectCodeTextReportWithViolations {
            get {
                return ResourceManager.GetString("ReSharperInspectCodeTextReportWithViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Generated by JetBrains Inspect Code 2021.3.2 --&gt;
        ///&lt;Report ToolsVersion=&quot;213.0.20211222.101123&quot;&gt;
        ///  &lt;Information&gt;
        ///     &lt;Solution&gt;..\..\..\..\..\..\..\github\Cake.ReSharper.GlobalTools\Cake.ReSharper.GlobalTools.sln&lt;/Solution&gt;
        ///    &lt;InspectionScope&gt;
        ///      &lt;Element&gt;Solution&lt;/Element&gt;
        ///    &lt;/InspectionScope&gt;
        ///  &lt;/Information&gt;
        ///  &lt;IssueTypes&gt;&lt;/IssueTypes&gt;
        ///  &lt;Issues&gt;&lt;/Issues&gt;
        ///&lt;/Report&gt;.
        /// </summary>
        internal static string ReSharperInspectCodeXmlReportNoViolations {
            get {
                return ResourceManager.GetString("ReSharperInspectCodeXmlReportNoViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Generated by JetBrains Inspect Code 2021.3.2 --&gt;
        ///&lt;Report ToolsVersion=&quot;213.0.20211222.101123&quot;&gt;
        ///  &lt;Information&gt;
        ///    &lt;Solution&gt;..\..\..\..\..\..\..\github\Cake.ReSharper.GlobalTools\Cake.ReSharper.GlobalTools.sln&lt;/Solution&gt;
        ///    &lt;InspectionScope&gt;
        ///      &lt;Element&gt;Solution&lt;/Element&gt;
        ///    &lt;/InspectionScope&gt;
        ///  &lt;/Information&gt;
        ///  &lt;IssueTypes&gt;
        ///    &lt;IssueType Id=&quot;AutoPropertyCanBeMadeGetOnly.Global&quot; Category=&quot;Common Practices and Code Improvements&quot; CategoryId=&quot;BestPra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReSharperInspectCodeXmlReportWithViolations {
            get {
                return ResourceManager.GetString("ReSharperInspectCodeXmlReportWithViolations", resourceCulture);
            }
        }
    }
}
