//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cake.ReSharper.GlobalTools.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cake.ReSharper.GlobalTools.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Generated by InspectCode 8.2.1000.4527 --&gt;
        ///&lt;Report ToolsVersion=&quot;8.2&quot;&gt;
        ///  &lt;Information&gt;
        ///    &lt;Solution&gt;src\Cake.sln&lt;/Solution&gt;
        ///    &lt;InspectionScope&gt;
        ///      &lt;Element&gt;Solution&lt;/Element&gt;
        ///    &lt;/InspectionScope&gt;
        ///  &lt;/Information&gt;
        ///  &lt;IssueTypes&gt;&lt;/IssueTypes&gt;
        ///  &lt;Issues&gt;&lt;/Issues&gt;
        ///&lt;/Report&gt;.
        /// </summary>
        internal static string InspectCodeReportNoViolations {
            get {
                return ResourceManager.GetString("InspectCodeReportNoViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Generated by InspectCode 8.2.1000.4527 --&gt;
        ///&lt;Report ToolsVersion=&quot;8.2&quot;&gt;
        ///  &lt;Information&gt;
        ///    &lt;Solution&gt;src\Cake.sln&lt;/Solution&gt;
        ///    &lt;InspectionScope&gt;
        ///      &lt;Element&gt;Solution&lt;/Element&gt;
        ///    &lt;/InspectionScope&gt;
        ///  &lt;/Information&gt;
        ///  &lt;IssueTypes&gt;
        ///    &lt;IssueType Id=&quot;CSharpErrors&quot; Category=&quot;C# Compiler Errors&quot; Description=&quot;&quot; Severity=&quot;ERROR&quot; /&gt;
        ///  &lt;/IssueTypes&gt;
        ///  &lt;Issues&gt;
        ///    &lt;Project Name=&quot;Cake.Common&quot;&gt;
        ///      &lt;Issue TypeId=&quot;CSharpErrors&quot; File=&quot;Cake.Common.Tests\F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InspectCodeReportWithViolations {
            get {
                return ResourceManager.GetString("InspectCodeReportWithViolations", resourceCulture);
            }
        }
    }
}
